datasets:
  social_comments:
    path: viethq1906/UIT-VSMEC-Sentiment-Relabelled
    text_field: sentence
    label_field: sentiment
    name: Social Comments Dataset
    description: A dataset of social media comments for sentiment analysis.
  vietnamese_comments:
    path: ura-hcmut/UIT-VSFC
    text_field: text
    label_field: label
    name: Vietnamese Comments Dataset
    description: A dataset of Vietnamese comments for sentiment analysis.
  merged_dataset:
    path: viethq1906/UIT-VSMEC-VSFC-Merge
    text_field: sentence
    label_field: sentiment
    name: Merged Vietnamese Comments Dataset
    description: A merged dataset of Vietnamese comments for sentiment analysis.
  augmentation_dataset:
    path: viethq1906/UIT-VSFC-emotion-augmentation
    text_field: sentence
    label_field: sentiment
    name: Augmented Vietnamese Comments Dataset
    description: An augmented dataset of Vietnamese comments for sentiment analysis.