datasets:
  social_comments:
    path: viethq1906/UIT-VSMEC-Sentiment-Relabelled
    text_field: sentence
    label_field: sentiment
    name: Social Comments Dataset
    description: A dataset of social media comments for sentiment analysis.
  augmentation_dataset:
    path: viethq1906/UIT-VSFC-emotion-augmentation
    text_field: sentence
    label_field: sentiment
    name: Augmented Vietnamese Comments Dataset
    description: An augmented dataset of Vietnamese comments for sentiment analysis.
  vlsp2016_dataset:
    path: viethq1906/VLSP2016
    text_field: sentence
    label_field: sentiment
    name: VLSP 2016 Dataset
    description: A dataset of Vietnamese comments from the VLSP 2016 competition.